version: '3.8'

services:
  gateway:
    image: nginx:1.25.2-alpine
    container_name: gateway-cashier-service
    restart: always
    ports: 
      - "80:80"
      - "443:443"
  cashier:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cashier-service:1.0.0
    container_name: cashier-service
    # ports:
    #   - "80:80"
    restart: on-failure:10
    depends_on:
      - mysql-cashier
      
  mysql-cashier: 
    build: 
      context: ./
      dockerfile: MySqlDockerfile
    image: cashier-db:1.0.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
   
volumes:
  db-data: