version: '3.8'

services:
  # App backend se


# service name
  mysql: 
    build: 
      context: ./
      #build sql MySqlDockerfile create table
      dockerfile: MySqlDockerfile
    #set  image name:tag
    image: cashier-db:1.0.0
    container_name: mysql_container
    # load  environment from file .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # - db-data
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
   
volumes:
  db-data: