version: '3.8'

services:
  # App backend se

  mysql:
    build: .
    image: cashier-db:1.0.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
   
# Volumes
# volumes:
#   db-data:


# Networks to be created to facilitate communication between containers
networks:
  turingmysql:
