version: '3.8'

services:
  # App backend se

  mysql:
    build: .
    image: cashier-db:1.0.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1"        # Request 2 CPU cores
          memory: 256M       # Request 2 GB of memory
        reservations:
         cpus: "1"        # Reserve 1 CPU core
         memory: 1G       # Reserve 1 GB of memory

# Volumes
# volumes:
#   db-data:


# Networks to be created to facilitate communication between containers
networks:
  turingmysql:
